### ISSUE TITLE
Вложенные теги внутри атрибутов другого тега

### ISSUE THREAD

**Issue by StudioMaX** [Gemorroj/xBBCode#1]
Привет! Совершенно случайно нашёл этот форк оригинального проекта xbbcode, которым пользовался до сих пор (и страдал). Решил перевести один legacy-проект на этот форк, но столкнулся со следующей проблемой/вопросом.
У меня существует дополнительный тег [spoiler], которого не было в оригинальном проекте, и чтобы не разбираться в работе тегов он был реализован не через xbb, а заменой регулярным выражением в уже скомпилированном html-коде:

```php
        $content = $xbbcode->getHtml();

        while (preg_match('/\[(SPOILER|spoiler)\=(.+?)\](.+?)\[\/(SPOILER|spoiler)\]/si', $content)) {
            $content = preg_replace(
                '/\[(SPOILER|spoiler)\=(.+?)\](.+?)\[\/(SPOILER|spoiler)\]/si',
                '<div><div class=\'spoilertop\' style=\'cursor:pointer;\' onclick="show_hide_text(this)">$2 ▼</div><div class=\'spoilermain\' style="display:none">$3</div></div>',
                $content
            );
        }

        while (preg_match('/\[spoiler\](.+?)\[\/spoiler\]/si', $content)) {
            $content = preg_replace(
                '/\[spoiler\](.+?)\[\/spoiler\]/si',
                '<div><div class=\'spoilertop\' style=\'cursor:pointer;\' onclick="show_hide_text(this)">▼</div><div class=\'spoilermain\' style="display:none">$1</div></div>',
                $content
            );
        }
```

Таким образом, сейчас на проекте спойлер работает, но пользователи нашли один баг, который стал фичей (и головной болью): он может быть как без заголовка, так и с заголовком с любым форматированием. Например:

```
[spoiler]Содержимое[/spoiler]
[spoiler=Заголовок спойлера]Содержимое[/spoiler]
[spoiler="[size=3]Заголовок спойлера[/size]"]Содержимое[/spoiler]
[spoiler=[size=3]Заголовок спойлера[/size]]Содержимое[/spoiler]
[spoiler="[size="3"]Заголовок спойлера[/size]"]Содержимое[/spoiler]
```
и ещё куча всевозможных форматирований заголовка спойлера. Из-за этой фичи не представляется возможным реализовать этот тег напрямую через Теги, а не через регулярку.

Пример реализации данного спойлера через Тег: https://gist.github.com/StudioMaX/3533a6a69ae8080ede3d4dd2430a6b26

К сожалению, удалось добиться работы только следующих вариантов:
```
[spoiler]Содержимое[/spoiler]
[spoiler=Заголовок спойлера]Содержимое[/spoiler]
[spoiler="[size=3]Заголовок спойлера[/size]"]Содержимое[/spoiler]
```
но вот со следующими проблема (для краткости буду писать только сам отображаемый заголовок, а не html-код)
Первый: `[spoiler=[size=3]Заголовок спойлера[/size]]Содержимое[/spoiler]` - превращается в `[size=3"`
Второй: `[spoiler="[size="3"]Заголовок спойлера[/size]"]Содержимое[/spoiler]` - превращается в `"[size="3"`

Я попробовал понять логику парсера и подебажил код, в итоге понял что существует две разные проблемы:
В первом варианте парсер работает в режиме ONE_ATTRIBUTE, поэтому заголовок тега может работать без кавычек. Но так как не учитывается вложенность открывающихся/закрывающихся квадратных скобок парсер решает, что закрывющаяся квадратная скобка после `size=3]` закрывает основной тег `spoiler`, хотя на самом деле она должна считаться простым текстом (а не управляющим символом).
Во втором варианте проблема в том, что не учитывается вложенность кавычек друг в друга. Это скорее даже базовая проблема, т.к. не работают конструкции вида [img src="something" title="есть "кавычки" в тайтле"].
Попробовал исправить это в методе парсера `finiteAutomaton()`, создав счётчики и проверяя, что количество открывшихся кавычек/квадратных скобок должно быть равно количеству закрывшихся, но в итоге сдался так и не получив результата.

Может быть Вы лучше сможете понять логику парсера? Или лучше забить на этот тег и оставить всё работать через регулярку?

**Comment by Gemorroj** [comment]
Привет.
Если честно, проект давно не трогал и уже позабыл что там и как.
Поддерживаю только работоспособность на новых версиях php.
Тэг Spoiler вроде как есть в форке https://github.com/Gemorroj/xBBCode/blob/master/src/Tag/Spoiler.php

По проблеме, я бы оставил регулярку)

**Comment by StudioMaX** [comment]
Тот что в форке не подходит под замену уже существующему, много старого bb-кода.
Значит будем дальше жить с регуляркой, может ещё лет через пять что-нибудь придумается :)
