### ISSUE TITLE
Please, create tag 2.6.1 for latest php 7.4 commit

### ISSUE THREAD

**Issue by AndryG** [Gemorroj/xBBCode#6]
Thank

**Comment by Gemorroj** [comment]
done!
https://github.com/Gemorroj/xBBCode/releases/tag/2.6.2
checrry picked https://github.com/Gemorroj/xBBCode/commit/93ac001894ebf8b3f9f2708eb6ab44a732be87a0 https://github.com/Gemorroj/xBBCode/commit/42796b392965c1d08f5b4af9b43cf86ec0b34299
