### ISSUE TITLE
2.6.1

### ISSUE THREAD

**Issue by AndryG** [Gemorroj/xBBCode#7]
Спасибо за ветку для php7.4
Только вы ее сделали не с того источника. Я ожидал, что в ней не будет лишь последней ревизии, которая ломает совместимость с php7.4, а вы сделали с ревизии 2,6,0. И потерялись коммиты:

Ревизия: 1ab4101237d0b13dae805be9fa4f99c24cdb07e2
Автор: Gemorroj <wapinet@mail.ru>
Дата: 21.12.2022 23:42:00
Сообщение:
build: drop php 7.3

Ревизия: 0ca975b284c5d0de85f94a89c75dd2b9e7561fec
Автор: Gemorroj <wapinet@mail.ru>
Дата: 08.01.2023 14:52:30
Сообщение:
refactoring: refactoring, added langs - dart, julia, kotlin, nginx conf, rust, saas, swift

И теперь, после перехода на 2,6,2 у меня сыпятся ошибки в моих классах-наследниках, ибо исчезли изменения с указанных транзаций (вы добавили там типы в палях).

Переделайте, пжлст, ветку 2,6,х с транзакции
Ревизия: 42796b392965c1d08f5b4af9b43cf86ec0b34299
Автор: Gemorroj <wapinet@mail.ru>
Дата: 28.06.2023 10:43:16
Сообщение:
fix: support https://html.spec.whatwg.org/#valid-navigable-target-name for target attribute
#5

Спасибо.

**Comment by Gemorroj** [comment]
я бы предложил использовать в качестве версии вариант `dev-master#42796b392965c1d08f5b4af9b43cf86ec0b34299`

**Comment by AndryG** [comment]
Спасибо. Варианта, как указать конкретный коммит я сам не нашел.

**Comment by AndryG** [comment]
Problem 1
    - Root composer.json requires gemorroj/xbbcode dev-master#42796b392965c1d08f5b4af9b43cf86ec0b34299 -> satisfiable by gemorroj/xbbcode[dev-master].
    - gemorroj/xbbcode dev-master requires php >=8.0.2 -> your php version (7.4.12) does not satisfy that requirement.
    
:) Таки остановлюсь на своем форке.

**Comment by Gemorroj** [comment]
хм, да. проблемка. тогда можно попробовать `dev-branch-2.6.0#42796b392965c1d08f5b4af9b43cf86ec0b34299` но лучше действительно форкнуть проект. т.к. бранч `branch-2.6.0` я рано или поздно удалю.

**Comment by AndryG** [comment]
А если с ревизии Ревизия: https://github.com/Gemorroj/xBBCode/commit/42796b392965c1d08f5b4af9b43cf86ec0b34299
Автор: Gemorroj [wapinet@mail.ru](mailto:wapinet@mail.ru)
Дата: 28.06.2023 10:43:16 сделать релиз "2.6.3" и это будет последний с php74?

**Comment by Gemorroj** [comment]
https://github.com/Gemorroj/xBBCode/releases/tag/2.6.3 готово.
